# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cakes')),
                ('name', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=50)),
                ('big_description', models.TextField(max_length=250)),
                ('available', models.BooleanField(default=True)),
                ('mixitup', multiselectfield.db.fields.MultiSelectField(choices=[('cake', 'Cake'), ('bread', 'Bread'), ('chocolate', 'Chocolate'), ('butter', 'Butter'), ('sweet', 'Sweet')], max_length=33)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCakeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='custom-cakes')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_needed', models.DateTimeField()),
                ('type', models.CharField(choices=[('round cake', 'Round Cake'), ('sheet cake', 'Sheet Cake')], max_length=50)),
                ('size', models.CharField(choices=[('6 inch round', '6 Inch Round'), ('8 inch round', '8 Inch Round'), ('10 inch round', '10 Inch Round'), ('12 inch round', '12 Inch Round'), ('12 inch round', '12 Inch Round'), ('1/4 sheet', '1/4 Sheet'), ('1/2 sheet', '1/2 Sheet'), ('3/4 sheet', '3/4 Sheet'), ('full sheet', 'Full Sheet')], max_length=50)),
                ('servings', models.PositiveIntegerField()),
                ('tiers', models.PositiveIntegerField()),
                ('flavor', models.CharField(choices=[('white', 'White'), ('chocolate', 'Chocolate'), ('marble', 'Marble'), ('red velvet', 'Red Velvert'), ('tiramisu', 'Tiramisu')], max_length=10)),
                ('filling1', models.CharField(choices=[('strawberry', 'Strawberry'), ('truffle whipped cream', 'Truffle Whipped Cream'), ('vanilla custard', 'Vanilla Custard'), ('cream cheese filling', 'Cream Cheese Filling')], max_length=50)),
                ('filling2', models.CharField(blank=True, choices=[('buttercream', 'Buttercream'), ('fondat', 'Fondat'), ('chocolate ganache', 'Chocolate Ganache')], max_length=50)),
                ('filling3', models.CharField(blank=True, choices=[('burnt almond', 'Burnt Almond'), ('raindbow sprinkles', 'Rainbow Sprinkles')], max_length=50)),
                ('frosting_color', models.CharField(max_length=50)),
                ('decoration_colors', models.CharField(blank=True, max_length=100)),
                ('writing', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='custom-cakes')),
                ('message', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customcake', to='orders.Order')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomCakeOrderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
