# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrderConfigOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('form_type', models.CharField(choices=[('date', 'Date'), ('dropdown', 'Dropdown'), ('input', 'input')], max_length=50)),
                ('sort', models.PositiveIntegerField(default=9999)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomCakeOrderConfig',
            new_name='CustomCakeOrderConfigOptionItem',
        ),
    ]
