# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cakes', '0002_auto_20180816_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorderconfigoptionitem',
            name='config_option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='config_option_item', to='custom_cakes.CustomCakeOrderConfigOption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcakeorderconfigoptionitem',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcakeorderconfigoptionitem',
            name='sort',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
