# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 02:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='about')),
                ('banner_image2', models.ImageField(upload_to='about')),
                ('mission', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faderimage1', models.ImageField(upload_to='home')),
                ('faderimage2', models.ImageField(blank=True, upload_to='home')),
                ('faderimage3', models.ImageField(blank=True, upload_to='home')),
                ('cake1_image', models.ImageField(blank=True, upload_to='home')),
                ('cake1_title', models.CharField(max_length=50)),
                ('cake1_description', models.CharField(max_length=75)),
                ('cake2_image', models.ImageField(blank=True, upload_to='home')),
                ('cake2_title', models.CharField(max_length=50)),
                ('cake2_description', models.CharField(max_length=75)),
                ('cake3_image', models.ImageField(blank=True, upload_to='home')),
                ('cake3_title', models.CharField(max_length=50)),
                ('cake3_description', models.CharField(max_length=75)),
                ('banner_image', models.ImageField(upload_to='home')),
                ('cart_banner_image', models.ImageField(upload_to='home')),
            ],
            options={
                'verbose_name': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
    ]
