# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180817_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='WEB', max_length=100),
            preserve_default=False,
        ),
    ]
