# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 21:16
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[800, 800], upload_to='products'),
        ),
    ]
