# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180816_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
